### PR TITLE
Fix nml object use

### LINKED ISSUE #22: Current passing of nmls as single object triggers unnecessary rebuilds w/ change to lake ids vector
I noticed while working with a subset of [`p1_lake_cell_tile_xwalk_df`](https://github.com/USGS-R/lake-temperature-process-models/blob/main/1_prep.R#L16-L19) to test code to package up the GLM output (#20, #21) that if I added a new site_id _after_ having run the models for the existing subset of lakes, that _all_ of the models rebuilt, which is definitely not the behavior we want. After digging a bit I realized it was due to an oversight in how I'm passing the nmls to `run_glm3_model()` when building `p2_glm_uncalibrated_runs`. Since we are mapping over `p1_model_config` to build `p2_glm_uncalibrated_runs`, which has 18 rows per lake, we couldn't also map over `p1_nml_objects`, which has 1 nested list element per lake. Therefore I passed in the full set of nml objects (`p1_nml_objects`) which gets updated each time the vector of site_ids changes. That's triggering the unnecessary rebuilds.

After talking it through, and some investigation of `targets` options on Lindsay's part, Lindsay and I decided that the best approach would be to save the nmls as files after [we modify them](https://github.com/USGS-R/lake-temperature-process-models/blob/main/1_prep/src/munge_nmls.R#L31-L49), and then add the nml filepath to the model config when we [build it](https://github.com/USGS-R/lake-temperature-process-models/blob/main/1_prep/src/build_model_config.R#L11-L41), so that within `run_glm_3_model()` we can simply read in the nml file, instead of [loading it from the list of nml objects](https://github.com/USGS-R/lake-temperature-process-models/blob/main/2_run/src/run_glm3.R#L105). That way we won't need to pass in `p1_nml_objects` as an argument to build `p2_glm_uncalibrated_runs`.

### PR DESCRIPTION
**Pull request by hcorson-dosch-usgs**
Fixes #22 

When I started to dig into #22, I realized that it was possible to make this fix without writing each of the nml objects to file, so I instead implemented an objects-based fix here.

This PR:
  * Adds list iteration to the `p1_nml_objects` list of nml objects
  * Maps over that `p1_nml_objects` in the target recipe for `p2_glm_uncalibrated_runs`, but does so as part of a `cross()` with `p1_gcm_names` and `p1_gcm_dates`, which means that each nml object is repeated 18 times - once for each gcm-time-period combination. That matches the [construction](https://github.com/USGS-R/lake-temperature-process-models/blob/main/1_prep/src/build_model_config.R#L32-L35) of `p1_model_config`, which means that the nml object passed to each branch of `p2_glm_uncalibrated_runs` is the correct nml object for that model run.

I tested this out for a subset of 5 lakes. If I first run the model for 4 of the lakes, and then add another site_id for a 5th lake, only the models for that 5th lake are built. Similarly if I run the model for 4 of the lakes and then _remove_ one of those site_ids, none of the models are rebuilt. That's the behavior we want, and corrects the issue noted in #22.

### CODE REVIEW

**Comment by hcorson-dosch-usgs** [comment]
Also wanted to note that I tested the mapping by doing the following:

1. Subsetting `p1_lake_cell_tile_xwalk` to 5 lakes:
```r
tar_target(p1_lake_cell_tile_xwalk_df, 
             readr::read_csv(p1_lake_cell_tile_xwalk_csv, col_types=cols()) %>%
               filter(site_id %in% p1_nml_site_ids) %>%
               arrange(site_id) %>%
               filter(site_id %in% c('nhdhr_105567868','nhdhr_105569520', 'nhdhr_114336097',
                                     'nhdhr_120019185','nhdhr_114544667'))),
```
2. Passing `p1_gcm_names` and `p1_gcm_dates` to the `run_glm3_model()` command:
```r
tar_target(
    p2_glm_uncalibrated_runs,
    run_glm3_model(
      sim_dir = '2_run/tmp/simulations',
      nml_obj = p1_nml_objects,
      gcm_name = p1_gcm_names,
      gcm_date = p1_gcm_dates,
      model_config = p1_model_config,
      burn_in = 300,
      burn_out = 190,
      export_fl_template = '2_run/tmp/GLM_%s_%s_%s.feather'),
    packages = c('retry','glmtools', 'GLM3r'),
    pattern = map(p1_model_config, cross(p1_nml_objects, p1_gcm_names, p1_gcm_dates))),
```
3.  Modifying `run_glm3_model` to return a tibble to check that the pertinent parameters match:
```r
run_glm3_model <- function(sim_dir, nml_obj, gcm_name, gcm_date, model_config, burn_in, burn_out, export_fl_template) {
  # pull parameters from model_config
  site_id <- model_config$site_id
  time_period <- model_config$time_period
  gcm <- model_config$gcm
  raw_meteo_fl <- model_config$meteo_fl
  
  mapping_check <- tibble(
    config_site_id = site_id,
    nml_site_id = nml_obj$morphometry$lake_name,
    config_gcm = gcm,
    mapped_gcm = gcm_name,
    config_time_period = time_period,
    mapped_time_period = gcm_date
  )
  return(mapping_check)
```
In the resulting tibble, you can see that the mapping set up by `cross(p1_nml_objects, p1_gcm_names, p1_gcm_dates)` matches the order of `p1_model_config`:
image

File: 2_run.R [hunk 1]
```diff
@@ -8,13 +8,13 @@ p2 <- list(
...
       sim_dir = '2_run/tmp/simulations',
-      nml_objs = p1_nml_objects,
+      nml_obj = p1_nml_objects,
       model_config = p1_model_config,
       burn_in = 300,
       burn_out = 190,
       export_fl_template = '2_run/tmp/GLM_%s_%s_%s.feather'),
     packages = c('retry','glmtools', 'GLM3r'),
-    pattern = map(p1_model_config)),
+    pattern = map(p1_model_config, cross(p1_nml_objects, p1_gcm_names, p1_gcm_dates))),
```
Comment (lindsayplatt) [inline 2_run.R:21]: I know that you noted that this "matches the [construction](https://github.com/USGS-R/lake-temperature-process-models/blob/main/1_prep/src/build_model_config.R#L32-L35) of p1_model_config", but that assumes we don't edit the `model_config()` function to reorder them in any way. 

We could hit some pretty mysterious issues if there is a mismatch at all and it would probably be hard to figure them out. Here is my reprex for a scenario where they aren't in the same order and we get branches with mismatched criteria. I think we need a very clear way to ensure that they are in the correct order.

```r
# For example, if the elements inside of `cross()` are not in the same order as the config table, we get mismatched branching
tar_target(maptbl, tibble(site = rep(c("s1","s2", "s3"), 2), model = c(rep("A", 3), rep("B", 3)))),
  tar_target(maplist, list(s2 = "s2 nml", s3 = "s3 nml", s1 = "s1 nml"), iteration = "list"),
  tar_target(mapvec, c("gcm A", "gcm B")),
  tar_target(
    test_pattern,
    tibble(map1 = maptbl,
           cross1 = maplist,
           cross2 = mapvec),
    pattern = map(maptbl, cross(maplist, mapvec))
  )

# Here is what you get after running tar_read(test_pattern)
# A tibble: 6 x 3
  map1$site $model cross1 cross2
  <chr>     <chr>  <chr>  <chr> 
1 s1        A      s2 nml gcm A 
2 s2        A      s2 nml gcm B 
3 s3        A      s3 nml gcm A 
4 s1        B      s3 nml gcm B 
5 s2        B      s1 nml gcm A 
6 s3        B      s1 nml gcm B 
```

I think this could be a good use-case for adding [`tar_assert`](https://rdrr.io/cran/targets/man/tar_assert.html)!! I haven't used it before, but have had my eye on this functionality. I _think_ it must go inside of a target command. The following does work as expected:

```r
tar_target(maptbl, tibble(site = rep(c("s1","s2", "s3"), 2), model = c(rep("A", 3), rep("B", 3)))),
  tar_target(maplist, list(s2 = "s2 nml", s3 = "s3 nml", s1 = "s1 nml"), iteration = "list"),
  tar_target(mapvec, c("gcm A", "gcm B")),
  tar_target(
    test_pattern, {
      tar_assert_identical(maptbl$site, names(maplist), "p1_nml_objects site order doesn't match p1_model_config")
      tibble(map1 = maptbl,
             cross1 = maplist,
             cross2 = mapvec)
    },
    pattern = map(maptbl, cross(maplist, mapvec))
  ),

# And this stops the pipeline and throws the following error
Error : p1_nml_objects site order doesn't match p1_model_config
```

**Review by lindsayplatt — COMMENTED** [review]
I am hesitant about the assumptions we are making with using `cross()` here + the `map()` over the config table. I have an idea for how to make this a more confident chunk of code. Otherwise, looks good! I like that you were able to use `iteration = 'list'` and some creative mapping to get around the need to write out individual files.

File: 2_run.R (hunk 1 above)
Comment (hcorson-dosch-usgs) [reply 2_run.R:21]: What a cool little bit of functionality! I've added a `tar_assert_identical()` check for the site ids and tested it, and it works just as expected!

**Review by lindsayplatt — APPROVED** [review]
Good to go!
